### PR TITLE
Create necessary files for running Hub

### PR DESCRIPTION
**Pull request by ravila4**
- Created hub.py
- Set up config_hub.py and config_web .py with parameters for local development.
- Updated packages in requirements_hub.txt to work with Python 3.8.
- Documented setup in README

### CODE REVIEW

**Comment by dongbohu** [comment]
@ravila4: Thank you very much for the PR. I don't know how you guys collaborate on GitHub. Do you need me to review the PR?

**Comment by ravila4** [comment]
Hi @dongbohu I think @newgene will accept the PR, but please feel free to look over the code, and try installing in your local machine. I tried to include all the necessary steps in the README, but please let me know if you need any help!

**Comment by dongbohu** [comment]
Thank you @ravila4. I will try it tomorrow.

**Comment by ravila4** [comment]
@dongbohu sounds good. I got feedback from @newgene, and updated the README. I'm merging the PR.

**Pull request merged**
